version: '3.8'

services:
  estate-ai:
    build: .
    container_name: estate-ai-container
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./model:/app/model
    restart: always
