apiVersion: apps/v1
kind: Deployment
metadata:
  name: estateai-deployment
  namespace: estateai-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estateai
  template:
    metadata:
      labels:
        app: estateai
    spec:
      containers:
      - name: estateai-container
        image: bittush8789/estateai-pro:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: estateai-service
  namespace: estateai-prod
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: estateai
